Repository FlySamryong/Meodeun_Daeyeo_frontend, pull requests merged in 2024-11, with the labels that each got.

#3 :recycle: [Refactor] 코드 리팩토링 및 코드 분할
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  lib/ui/chat/chat_page.dart
  lib/ui/widget/chat_message/amount_dialog.dart
  lib/ui/widget/chat_message/chat_message_list.dart
  lib/ui/widget/chat_message/common_dialog.dart
  lib/ui/widget/chat_message/message_input_field.dart
  lib/ui/widget/chat_message/message_popup_menu.dart
  lib/ui/widget/chat_message/return_code_dialog.dart
  lib/ui/widget/chat_message/return_verification_dialog.dart
Labels: enhancement

#6 :bug: [Bug] 로그인 api 연동 오류 수정
  lib/service/api_client.dart
  lib/service/auth/service/auth_service.dart
  lib/ui/home/item_list.dart
Labels: bug

#8 [Feat] 채팅, 대여 서비스 api 연동 기능 추가
  lib/service/account/account_service.dart
  lib/service/rent/rent_service.dart
  lib/ui/chat/chat_message/chat_message.dart
  lib/ui/chat/chat_message/chat_message_list.dart
  lib/ui/chat/chat_message/chat_page.dart
  lib/ui/chat/chat_message/dialog/amount_dialog.dart
  lib/ui/chat/chat_message/dialog/common_dialog.dart
  lib/ui/chat/chat_message/dialog/date_input_dialog.dart
  lib/ui/chat/chat_message/dialog/return_code_dialog.dart
  lib/ui/chat/chat_message/dialog/return_deposit_dialog.dart
  lib/ui/chat/chat_message/dialog/return_verification_dialog.dart
  lib/ui/chat/chat_message/message_input_field.dart
  lib/ui/chat/chatting_list/chat_card.dart
  lib/ui/chat/chatting_list/chat_list.dart
  lib/ui/item/detail/action_button.dart
  lib/ui/mypage/accout_register/account_registeration_dialog.dart
  lib/ui/mypage/profile/my_page.dart
  lib/ui/mypage/profile/profile_section.dart
  lib/utils/date_time_formatter.dart
  lib/utils/rent_id_storage.dart
Labels: enhancement

#9 :bug: [Bug] 송/수신자 간에 rentId 공유 안되는 오류 수정
  lib/ui/chat/chat_message/chat_message.dart
  lib/ui/chat/chat_message/chat_page.dart
Labels: :lady_beetle: BugFix

#13 [Feat] 대여 목록 조회, 관심 목록 조회 및 등록 api 연동 추가
  lib/service/member/member_service.dart
  lib/ui/favorite/FavoriteItemListWidget.dart
  lib/ui/item/detail/action_button.dart
  lib/ui/mypage/rent_history/rental_history_item.dart
  lib/ui/mypage/rent_history/rental_list.dart
  lib/utils/show_success_dialog.dart
Labels: :mailbox: API, :sparkles: Feature

#21 :bug: [Bug] 최근 조회 물품 목록에서 상세 페이지로 이동 안되던 오류 수정
  lib/ui/mypage/recent_item/recent_view_item_page.dart
  lib/ui/mypage/recent_item/recently_view_item.dart
  lib/ui/mypage/recent_item/recently_view_list.dart
Labels: :hammer: Refactor, :lady_beetle: BugFix, :mailbox: API

#25 ✨ [Feat] : 유저의 장소 업데이트 기능추가
  lib/ui/mypage/location_register/location_registeration_dialog.dart
  lib/ui/mypage/profile/my_page.dart
  lib/ui/mypage/profile/profile_section.dart
Labels: :sparkles: Feature
